nameOverride: ""
fullnameOverride: ""

replicaCount: 1
application:
  port: 80
  profile: dev

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  nodePort:

serviceAccount:
  create: false
  annotations: {}
  name: ""

image:
  repository: harbor.ha-ving.store/docker/711-community
  tag: "8c52a17264dd59addd40f334c75ffafcfcab5822"
  pullPolicy: IfNotPresent

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60

ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "ha-ving.store-issuer"
    nginx.ingress.kubernetes.io/proxy_connect_timeout: "600"
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"
    nginx.ingress.kubernetes.io/proxy-rad-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/send-timeout: "600"
    nginx.ingress.kubernetes.io/limit-connections: "20"
  hosts:
    - host: 711.ha-ving.store
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: 711-ingress
      hosts:
        - 711.ha-ving.store

resources:
  limits:
    cpu: 2000m
    memory: 2048Mi
  requests:
    cpu: 1000m
    memory: 1024Mi

volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

nodeSelector: {}

tolerations: []

affinity: {}