-- refresh token
insert into refresh_tokens (expire_at,token_value,token_key) values (1719994805831,'Bearer eyJhbGciOiJIUzUxMiJ9.eyJpbWFnZSI6Imh0dHBzOi8vYXZhdGFycy5naXRodWJ1c2VyY29udGVudC5jb20vdS83OTI3MDIyOD92PTQiLCJwYXNzd29yZCI6IiQyYSQxMCRoTWcuYzhDL3VseFJkSjdLMEs4L2F1bVVPdTQ5UmtUTEF0eUliYVh0aDFIUWVGUU9MMC9iSyIsInBob25lIjoiMDEwMTExMTIyMjIiLCJyb2xlcyI6WyJST0xFX1VTRVIiXSwibmlja25hbWUiOiJuaWNrbmFtZTEiLCJpZCI6MjEsInVzZXJuYW1lIjoidXNlciIsImF1dGgiOiJST0xFX1VTRVIiLCJpYXQiOjE3MTczMTY0MDUsImV4cCI6MTcxOTk5NDgwNX0.uAuo_EaWOx-ghXxByoXFnMl8iXqWFPjQQexXRZp6uZHosH8ksNUjk6BxOzICDQeYNrH-vg-OGPJEa6DkBIN0FA','user');

-- user
insert into users (image,nickname,password,phone,username,id, house_id) values ('https://avatars.githubusercontent.com/u/79270228?s=80&v=4','nick1','$2a$10$Pg9UFHmGqfDBvqydetjeweDJLpgos79DnpvZfMWOTOIUnx4oBADFq',NULL,'user1',default, 1);
insert into users (image,nickname,password,phone,username,id) values ('https://avatars.githubusercontent.com/u/79270228?s=80&v=4','nick2','$2a$10$Pg9UFHmGqfDBvqydetjeweDJLpgos79DnpvZfMWOTOIUnx4oBADFq',NULL,'user2',default);
insert into users (image,nickname,password,phone,username,id, house_id) values ('https://avatars.githubusercontent.com/u/79270228?s=80&v=4','nick3','$2a$10$Pg9UFHmGqfDBvqydetjeweDJLpgos79DnpvZfMWOTOIUnx4oBADFq',NULL,'user3',default, 2);
insert into users (image,nickname,password,phone,username,id) values ('https://avatars.githubusercontent.com/u/79270228?s=80&v=4','nick4','$2a$10$Pg9UFHmGqfDBvqydetjeweDJLpgos79DnpvZfMWOTOIUnx4oBADFq',NULL,'user4',default);
insert into users (image,nickname,password,phone,username,id) values ('https://avatars.githubusercontent.com/u/79270228?s=80&v=4','nick5','$2a$10$Pg9UFHmGqfDBvqydetjeweDJLpgos79DnpvZfMWOTOIUnx4oBADFq',NULL,'user5',default);
insert into users (image,nickname,password,phone,username,id) values ('https://avatars.githubusercontent.com/u/79270228?s=80&v=4','nick6','$2a$10$Pg9UFHmGqfDBvqydetjeweDJLpgos79DnpvZfMWOTOIUnx4oBADFq',NULL,'user6',default);
insert into users (image,nickname,password,phone,username,id) values ('https://avatars.githubusercontent.com/u/79270228?s=80&v=4','nick7','$2a$10$Pg9UFHmGqfDBvqydetjeweDJLpgos79DnpvZfMWOTOIUnx4oBADFq',NULL,'user7',default);
insert into users (image,nickname,password,phone,username,id) values ('https://avatars.githubusercontent.com/u/79270228?s=80&v=4','nick8','$2a$10$Pg9UFHmGqfDBvqydetjeweDJLpgos79DnpvZfMWOTOIUnx4oBADFq',NULL,'user8',default);
insert into users (image,nickname,password,phone,username,id) values ('https://avatars.githubusercontent.com/u/79270228?s=80&v=4','nick9','$2a$10$Pg9UFHmGqfDBvqydetjeweDJLpgos79DnpvZfMWOTOIUnx4oBADFq',NULL,'user9',default);
insert into users (image,nickname,password,phone,username,id) values ('https://avatars.githubusercontent.com/u/79270228?s=80&v=4','nick10','$2a$10$Pg9UFHmGqfDBvqydetjeweDJLpgos79DnpvZfMWOTOIUnx4oBADFq',NULL,'user10',default);
insert into users (image,nickname,password,phone,username,id) values ('https://avatars.githubusercontent.com/u/79270228?s=80&v=4','nick11','$2a$10$Pg9UFHmGqfDBvqydetjeweDJLpgos79DnpvZfMWOTOIUnx4oBADFq',NULL,'user11',default);
insert into users (image,nickname,password,phone,username,id) values ('https://avatars.githubusercontent.com/u/79270228?s=80&v=4','nick12','$2a$10$Pg9UFHmGqfDBvqydetjeweDJLpgos79DnpvZfMWOTOIUnx4oBADFq',NULL,'user12',default);
insert into users (image,nickname,password,phone,username,id) values ('https://avatars.githubusercontent.com/u/79270228?s=80&v=4','nick13','$2a$10$Pg9UFHmGqfDBvqydetjeweDJLpgos79DnpvZfMWOTOIUnx4oBADFq',NULL,'user13',default);
insert into users (image,nickname,password,phone,username,id) values ('https://avatars.githubusercontent.com/u/79270228?s=80&v=4','nick14','$2a$10$Pg9UFHmGqfDBvqydetjeweDJLpgos79DnpvZfMWOTOIUnx4oBADFq',NULL,'user14',default);
insert into users (image,nickname,password,phone,username,id) values ('https://avatars.githubusercontent.com/u/79270228?s=80&v=4','nick15','$2a$10$Pg9UFHmGqfDBvqydetjeweDJLpgos79DnpvZfMWOTOIUnx4oBADFq',NULL,'user15',default);
insert into users (image,nickname,password,phone,username,id) values ('https://avatars.githubusercontent.com/u/79270228?s=80&v=4','nick16','$2a$10$Pg9UFHmGqfDBvqydetjeweDJLpgos79DnpvZfMWOTOIUnx4oBADFq',NULL,'user16',default);
insert into users (image,nickname,password,phone,username,id) values ('https://avatars.githubusercontent.com/u/79270228?s=80&v=4','nick17','$2a$10$Pg9UFHmGqfDBvqydetjeweDJLpgos79DnpvZfMWOTOIUnx4oBADFq',NULL,'user17',default);
insert into users (image,nickname,password,phone,username,id) values ('https://avatars.githubusercontent.com/u/79270228?s=80&v=4','nick18','$2a$10$Pg9UFHmGqfDBvqydetjeweDJLpgos79DnpvZfMWOTOIUnx4oBADFq',NULL,'user18',default);
insert into users (image,nickname,password,phone,username,id) values ('https://avatars.githubusercontent.com/u/79270228?s=80&v=4','nick19','$2a$10$Pg9UFHmGqfDBvqydetjeweDJLpgos79DnpvZfMWOTOIUnx4oBADFq',NULL,'user19',default);
insert into users (image,nickname,password,phone,username,id) values ('https://avatars.githubusercontent.com/u/79270228?s=80&v=4','nick20','$2a$10$Pg9UFHmGqfDBvqydetjeweDJLpgos79DnpvZfMWOTOIUnx4oBADFq',NULL,'user20',default);

-- freepost
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (1, 11, '13 Fighting Men', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Herminia Janovsky', '2023-02-26 00:14:23', 86, true, false, 'FreePost', 12, 4, 20, 7, 6);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (2, 12, 'Wild Beasts (Wild beasts - Belve feroci)', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'Pinchas Fiveash', '2023-03-25 00:14:23', 40, true, false, 'FreePost', 12, 43, 79, 54, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (3, 13, 'The Woodcarver', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'Waverly Braunlein', '2023-04-26 00:14:23', 41, true, false, 'FreePost', 12, 11, 57, 57,1);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (4, 14, 'Everybody''s Fine (Stanno tutti bene)', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'Raimondo Popov', '2023-05-27 00:14:23', 93, false, false, 'FreePost', 12, 29, 12, 64,0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (5, 15, 'Last Play at Shea, The', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'Marlie Shaudfurth', '2023-09-30 00:14:23', 54, true, false, 'FreePost', 12, 49, 100, 31,0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (6, 16, 'Dead, The', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'Alix Keasy', '2023-10-11 00:14:23', 41, true, false, 'FreePost', 12, 12, 34, 67,0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (7, 17, 'News from Home', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'Rodrigo Brightling', '2023-12-18 00:14:23', 21, true, false, 'FreePost', 13, 15, 19, 97,0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (8, 18, 'Sugar Town', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'Lynn Mc Gorley', '2024-01-21 00:14:23', 84, true, false, 'FreePost', 13, 13, 88, 72,0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (9, 19, 'Liar''s Autobiography: The Untrue Story of Monty Python''s Graham Chapman, A', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'Dion Bushell', '2023-09-08 00:14:23', 12, false, false, 'FreePost', 13, 17, 87, 8,0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (10, 20, 'Son of Frankenstein', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 'Manfred Hatfull', '2024-02-08 00:14:23', 50, false, false, 'FreePost', 13, 24, 79, 21,0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (11, 1, 'The Amazing Spider-Man 2', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'Katharina Skacel', '2024-02-08 00:18:23', 39, false, false, 'FreePost', 13, 46, 94, 33,0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (12, 2, 'My Fellow Americans', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'Natasha Bantham', '2024-02-26 00:14:23', 23, false, false, 'FreePost', 13, 21, 91, 43,0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (13, 3, 'Failure to Launch', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 'Kalvin McMurraya', '2024-03-11 00:14:23', 20, false, false, 'FreePost', 14, 43, 51, 54,0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (14, 4, 'Shining Through', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'Cirstoforo Cropton', '2024-03-14 00:14:23', 29, false, false, 'FreePost', 14, 26, 33, 81,0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (15, 5, 'Charlie Chan in the Secret Service', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'Cheri Vaen', '2024-05-26 00:10:23', 108, false, false, 'FreePost', 14, 27, 24, 71,0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (16, 6, 'Billy''s Hollywood Screen Kiss', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'Ben Barneveld', '2024-05-26 00:14:23', 16, true, false, 'FreePost', 15, 12, 47, 90,0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (17, 7, 'Journey of Natty Gann, The', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Emili Itzcovichch', '2024-05-27 00:14:23', 15, false, false, 'FreePost', 7, 31, 23, 40,0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (18, 8, 'Tu£sday', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'Julian Blundin', '2024-05-29 00:14:23', 7, false, false, 'FreePost', 15, 30, 88, 94,0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (19, 9, 'Killing, The', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'Irving Richardet', '2024-05-30 00:14:23', 92, false, false, 'FreePost', 15, 2, 27, 44,0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (20, 10, 'Lara Croft: Tomb Raider', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 'Shep Cleveland', '2024-06-01 00:14:23', 12, true, false, 'FreePost', 15, 44, 28, 11,0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (21, 11, 'Boyhood', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 'Zebedee Pumfrey', '2024-06-02 00:14:23', 52, false, false, 'FreePost', 16, 21, 29, 93,0);

-- noticePost
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (22, 12, 'Unleashed (Danny the Dog)', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 'Kassi Konig', '2023-07-15 00:14:23', 56, false, false, 'NoticePost', 4, 11, 42, 76, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (23, 13, 'Staten Island', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'Johnnie Sealove', '2023-07-23 00:14:23', 27, true, false, 'NoticePost', 2, 13, 85, 16, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (24, 14, 'Gun in Betty Lou''s Handbag, The', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'Abram Lankham', '2024-04-08 00:14:23', 36, false, true, 'NoticePost', 9, 29, 35, 68, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (25, 15, 'OT: Our Town', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'Bellina Stitt', '2024-05-27 00:14:23', 65, false, true, 'NoticePost', 3, 2, 51, 39, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (26, 16, 'Redbelt', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Neils MacCheyne', '2023-07-08 00:14:23', 1, true, false, 'NoticePost', 10, 39, 46, 3, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (27, 17, 'Turning Tide (En solitaire)', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'Averil Muro', '2024-03-19 00:14:23', 25, true, false, 'NoticePost', 1, 49, 46, 42, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (28, 18, 'Running Out of Time (Am zin)', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'Inglis Talkington', '2024-04-25 00:14:23', 40, false, false, 'NoticePost', 1, 35, 85, 66, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (29, 19, 'Fingersmith', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'Jessalin Gambell', '2023-12-13 00:14:23', 53, true, false, 'NoticePost', 9, 1, 82, 77, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (30, 20, 'Stage Struck', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'Eugine Everiss', '2023-08-05 00:14:23', 46, false, false, 'NoticePost', 1, 18, 94, 45, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (31, 1, 'Awakening, The', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'Giffy Milesop', '2023-08-30 00:14:23', 20, false, false, 'NoticePost', 4, 4, 22, 75, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (32, 2, 'Countdown', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'Jesse Orris', '2024-05-24 00:14:23', 100, true, false, 'NoticePost', 8, 38, 88, 88, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (33, 3, 'Ossessione', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Ferris Prowting', '2023-07-11 00:14:23', 66, false, false, 'NoticePost', 7, 2, 54, 83, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (34, 4, 'Zabriskie Point', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'Lucas Tomaskov', '2024-05-24 00:14:23', 98, true, false, 'NoticePost', 10, 12, 47, 44, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (35, 5, 'Knuckleball!', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'Joleen Thrustle', '2023-12-20 00:14:23', 96, true, false, 'NoticePost', 1, 30, 58, 2, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (36, 6, 'Chad Hanna', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'Rogers Possell', '2024-01-12 00:14:23', 22, false, false, 'NoticePost', 5, 27, 39, 25, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (37, 7, 'Year of the Hare, The (Jäniksen vuosi)', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'Giselbert Angear', '2023-07-15 00:14:23', 3, true, false, 'NoticePost', 3, 37, 71, 49, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (38, 8, 'Out to Sea', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'Suki Roughsedge', '2024-04-29 00:14:23', 25, true, false, 'NoticePost', 9, 17, 72, 25, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (39, 9, '3 Little Ninjas and the Lost Treasure', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'Amandi Northin', '2023-06-01 00:14:23', 91, false, false, 'NoticePost', 5, 23, 8, 54, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (40, 10, 'Angelus', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'Corbet Keme', '2024-02-02 00:14:23', 25, false, false, 'NoticePost', 10, 22, 5, 67, 0);

-- qna
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (41, 11, '13 Fighting Men', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Herminia Janovsky', '2023-02-26 00:14:23', 86, true, false, 'QnaPost', 24, 4, 20, 7, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (42, 12, 'Wild Beasts (Wild beasts - Belve feroci)', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'Pinchas Fiveash', '2023-03-25 00:14:23', 40, true, false, 'QnaPost', 24, 43, 79, 54, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (43, 13, 'The Woodcarver', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'Waverly Braunlein', '2023-04-26 00:14:23', 41, true, false, 'QnaPost', 24, 11, 57, 57, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (44, 14, 'Everybody''s Fine (Stanno tutti bene)', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'Raimondo Popov', '2023-05-27 00:14:23', 93, false, false, 'QnaPost', 24, 29, 12, 64, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (45, 15, 'Last Play at Shea, The', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'Marlie Shaudfurth', '2023-09-30 00:14:23', 54, true, false, 'QnaPost', 24, 49, 100, 31, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (46, 16, 'Dead, The', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'Alix Keasy', '2023-10-11 00:14:23', 41, true, false, 'QnaPost', 24, 12, 34, 67, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (47, 17, 'News from Home', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'Rodrigo Brightling', '2023-12-18 00:14:23', 21, true, false, 'QnaPost', 24, 15, 19, 97, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (48, 18, 'Sugar Town', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'Lynn Mc Gorley', '2024-01-21 00:14:23', 84, true, false, 'QnaPost', 24, 13, 88, 72, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (49, 19, 'Liar''s Autobiography: The Untrue Story of Monty Python''s Graham Chapman, A', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'Dion Bushell', '2023-09-08 00:14:23', 12, false, false, 'QnaPost', 24, 17, 87, 8, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (50, 20, 'Son of Frankenstein', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 'Manfred Hatfull', '2024-02-08 00:14:23', 50, false, false, 'QnaPost', 24, 24, 79, 21, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (51, 1, 'The Amazing Spider-Man 2', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'Katharina Skac, 0el', '2024-02-08 00:18:23', 39, false, false, 'QnaPost', 24, 46, 94, 33, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (52, 2, 'My Fellow Americans', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'Natasha Bantham', '2024-02-26 00:14:23', 23, false, false, 'QnaPost', 24, 21, 91, 43, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (53, 3, 'Failure to Launch', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 'Kalvin McMurray, 0a', '2024-03-11 00:14:23', 20, false, false, 'QnaPost', 24, 43, 51, 54, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (54, 4, 'Shining Through', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'Cirstoforo Cropton', '2024-03-14 00:14:23', 29, false, false, 'QnaPost', 24, 26, 33, 81, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (55, 5, 'Charlie Chan in the Secret Service', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'Cheri Vaen', '2024-05-26 00:10:23', 108, false, false, 'QnaPost', 24, 27, 24, 71, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (56, 6, 'Billy''s Hollywood Screen Kiss', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'Ben Barneveld', '2024-05-26 00:14:23', 16, true, false, 'QnaPost', 24, 12, 47, 90, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (57, 7, 'Journey of Natty Gann, The', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Emili Itzcovichch', '2024-05-27 00:14:23', 98, false, false, 'QnaPost', 2, 04, 31, 23, 40);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (58, 8, 'Tu£sday', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'Julian Blundin', '2024-05-29 00:14:23', 7, false, false, 'QnaPost', 24, 30, 88, 94, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (59, 9, 'Killing, The', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'Irving Richardet', '2024-05-30 00:14:23', 92, false, false, 'QnaPost', 24, 2, 27, 44, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (60, 10, 'Lara Croft: Tomb Raider', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 'Shep Cleveland', '2024-06-01 00:14:23', 12, true, false, 'QnaPost', 24, 44, 28, 11, 0);

-- complain
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (61, 11, 'Wrong Turn at Tahoe', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'Georgetta Ram', '2024-04-15 00:14:23', 30, false, false, 'ComplaintPost', 1, 43, 52, 88, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (62, 12, 'Captain January', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'Sarajane Barde', '2023-08-01 00:14:23', 15, false, false, 'ComplaintPost', 4, 26, 17, 53, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (63, 13, 'Take the Money and Run', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'Anet Frickey', '2023-10-10 00:14:23', 62, false, false, 'ComplaintPost', 8, 2, 8, 64, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (64, 14, 'North and South, Book II', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'Katharina Zorzin', '2023-08-06 00:14:23', 60, false, false, 'ComplaintPost', 2, 24, 19, 87, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (65, 15, 'Indie Game: The Movie', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'Nessa Spencock', '2024-04-04 00:14:23', 84, true, false, 'ComplaintPost', 2, 34, 19, 57, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (66, 16, 'For a Good Time, Call...', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'Devlen Tafani', '2023-07-04 00:14:23', 60, true, false, 'ComplaintPost', 4, 45, 95, 36, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (67, 17, 'Rites of May, The (Itim) ', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'Bar Cathrae', '2023-06-18 00:14:23', 59, true, true, 'ComplaintPost', 9, 2, 89, 28, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (68, 18, 'Pianomania', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'Kiele Fosdike', '2023-11-30 00:14:23', 53, false, false, 'ComplaintPost', 2, 42, 32, 12, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (69, 19, 'Last Witness, The', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'Celia Joslyn', '2023-11-09 00:14:23', 94, true, false, 'ComplaintPost', 2, 42, 17, 16, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (70, 20, 'At Middleton', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'Janeen Enrrico', '2024-04-07 00:14:23', 25, false, false, 'ComplaintPost', 4, 6, 45, 72, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (71, 1, 'Crimson Petal and the White, The', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'Johnette Tunn', '2023-06-06 00:14:23', 93, false, false, 'ComplaintPost', 9, 24, 50, 31, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (72, 2, 'Darling', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'Danny Earie', '2023-06-07 00:14:23', 35, false, false, 'ComplaintPost', 4, 42, 12, 58, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (73, 3, 'Blue Gold: World Water Wars', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'Ezri Philpots', '2023-06-30 00:14:23', 72, false, false, 'ComplaintPost', 7, 10, 8, 66, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (74, 4, 'Sidekicks', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'Wells Potzold', '2024-06-01 00:14:23', 31, true, false, 'ComplaintPost', 1, 2, 79, 83, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (75, 5, 'Hard, Fast and Beautiful', 'Fusce consequat. Nulla nisl. Nunc nisl.', 'Stern Burrill', '2024-01-05 00:14:23', 19, true, false, 'ComplaintPost', 5, 14, 96, 86, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (76, 6, 'Emperor and the Assassin, The (Jing ke ci qin wang)', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'Merilee Jerome', '2024-04-08 00:14:23', 72, false, false, 'ComplaintPost', 7, 36, 83, 80, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (77, 7, 'Popular Music (Populärmusik från Vittula)', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Elliott Warner', '2024-05-12 00:14:23', 52, true, false, 'ComplaintPost', 7, 34, 92, 52, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (78, 8, 'Apple, The', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'Carole Codner', '2023-07-07 00:14:23', 33, false, false, 'ComplaintPost', 7, 20, 66, 20, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (79, 9, 'Going to Kansas City', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'Gracie Eate', '2024-03-05 00:14:23', 24, false, false, 'ComplaintPost', 5, 29, 14, 99, 0);

-- notice post (is_duty = true)
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (80, 10, 'French Fried Vacation 2 (Les bronzés font du ski)', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'Stevy Zanre', '2024-02-16 00:14:23', 65, false, false, 'NoticePost', 6, 1, 16, 60, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (81, 11, 'Nightcap (Merci pour le chocolat)', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'Lanae Spinelli', '2024-05-30 00:14:23', 88, false, false, 'NoticePost', 10, 28, 87, 98, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (82, 12, 'Jim Norton: Please Be Offended', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Ewell Hendrichs', '2024-03-19 00:14:23', 57, true, false, 'NoticePost', 1, 3, 91, 98, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (83, 13, 'Feuerzangenbowle, Die', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'Reta Skoate', '2023-08-08 00:14:23', 99, false, false, 'NoticePost', 1, 4, 49, 58, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (84, 14, 'Only Two Can Play', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'Kaylil Gatteridge', '2023-12-29 00:14:23', 77, false, false, 'NoticePost', 4, 14, 51, 28, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (85, 15, 'Moving Midway', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'Korney Muggleton', '2024-04-02 00:14:23', 19, true, false, 'NoticePost', 9, 27, 91, 60, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (86, 16, 'Shaka Zulu: The Citadel', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'Evanne Stacey', '2023-08-04 00:14:23', 75, false, false, 'NoticePost', 4, 25, 81, 29, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (87, 17, 'Our Lady of the Assassins (Virgen de los sicarios, La)', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'Dniren Gullen', '2024-03-07 00:14:23', 27, false, false, 'NoticePost', 5, 43, 57, 63, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (88, 18, 'Fight Club', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'Sawyere Sewill', '2024-03-23 00:14:23', 63, false, false, 'NoticePost', 4, 11, 82, 23, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (89, 19, 'Cass', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'Leisha Domange', '2023-07-14 00:14:23', 82, true, false, 'NoticePost', 3, 40, 6, 73, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (90, 20, 'Silent Action', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 'Rosmunda Garlic', '2023-09-02 00:14:23', 17, false, false, 'NoticePost', 6, 43, 84, 75, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (91, 1, 'Amorosa', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'Gayle Ghirigori', '2023-11-09 00:14:23', 72, false, false, 'NoticePost', 4, 20, 58, 12, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (92, 2, 'Nothing But the Truth', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'Klaus Cuningham', '2023-09-04 00:14:23', 74, false, false, 'NoticePost', 9, 8, 3, 5, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (93, 3, 'Back Door to Hell', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'Eda Wyke', '2024-04-11 00:14:23', 13, false, false, 'NoticePost', 8, 18, 62, 81, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (94, 4, 'Stand Up and Cheer!', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'Angeline Bilbey', '2023-08-19 00:14:23', 7, false, false, 'NoticePost', 10, 25, 62, 53, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (95, 5, 'Cyclomania', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 'Vincent Lown', '2023-06-09 00:14:23', 39, false, false, 'NoticePost', 10, 5, 83, 76, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (96, 6, 'Not with My Wife, You Don''t!', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'Kendall Daborne', '2023-12-15 00:14:23', 81, true, false, 'NoticePost', 10, 46, 86, 16, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (97, 7, 'Don''t Drink the Water', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'Mikaela Reinbach', '2023-12-24 00:14:23', 32, false, false, 'NoticePost', 6, 11, 33, 21, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (98, 8, 'Kind Lady', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'Carma Pilgrim', '2024-03-27 00:14:23', 83, false, false, 'NoticePost', 4, 33, 54, 76, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (99, 9, 'Room 666 (Chambre 666)', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'Brinn Lacase', '2024-01-27 00:14:23', 36, true, false, 'NoticePost', 2, 38, 94, 40, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (100, 10, 'Frailty', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'Pat Snooks', '2024-03-05 00:14:23', 30, true, false, 'NoticePost', 5, 16, 7, 20, 0);

-- market
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (101, 11, '13 Fighting Men', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Herminia ky', '2024-03-26 00:14:23', 81, true, false, 'MarketPost', 26, 4, 20, 7, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (102, 12, 'ting Men', 'atis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Hermanovsky', '2024-05-26 00:14:23', 82, true, false, 'MarketPost', 26, 4, 20, 7, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (103, 13, '13 Figh Men', 'usce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Hermia Janovsky', '2024-03-26 00:14:23', 83, true, false, 'MarketPost', 26, 4, 20, 7, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (104, 14, '1Dickie Robertsn', 'natis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'minia Janovsky', '2021-03-26 00:14:23', 84, true, false, 'MarketPost', 26, 4, 20, 7, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (105, 15, 'Fighting Men', 'nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'nia Janovsky', '2023-03-26 00:14:23', 85, true, false, 'MarketPost', 26, 4, 20, 7, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (106, 16, '1Dickie Roberts Men', 'ique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'inia Javsky', '2021-03-26 00:14:23', 86, true, false, 'MarketPost', 25, 4, 20, 7, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (107, 17, ' Fighting Dickie Roberts', 'atis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'inia anovsky', '2014-03-26 00:14:23', 46, true, false, 'MarketPost', 25, 4, 20, 7, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (108, 18, 'Dickie Roberts Fighting Men', 'a nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Hermnovsky', '2024-03-25 00:14:23', 87, true, false, 'MarketPost', 25, 4, 20, 7, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (109, 19, '13 Dickie Roberts Men', 'Vcinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Herminia Jansky', '2024-03-16 00:14:23', 46, true, false, 'MarketPost', 25, 4, 20, 7, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (110, 11, 'Cheerleader Fighting Men', 'Veacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Heinia Janovsky', '2014-03-16 00:14:23', 45, true, false, 'MarketPost', 25, 4, 20, 7, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (111, 12, '13 Fighting Cheerleader', 'Vesinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Herminia Janovsky', '2014-02-26 00:14:23', 43, true, false, 'MarketPost', 26, 4, 20, 7, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (112, 13, 'Men', 'Vei venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Herminia Jaovsky', '2024-01-22 00:14:23', 48, true, false, 'MarketPost', 26, 4, 20, 7, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (113, 14, 'ing Men', 'ia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Herinia Janovsky', '2024-03-22 00:14:23', 13, true, false, 'MarketPost', 26, 4, 20, 7, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (114, 15, 'hting Men', 'Vest lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Hermiovsky', '2014-08-26 00:14:23', 12, true, false, 'MarketPost', 26, 4, 20, 7, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (115, 16, '13 Fn', 'Vestibulum ac est ltis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Herminiavsky', '2024-01-26 00:14:23', 11, true, false, 'MarketPost', 26, 4, 20, 7, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (116, 17, '13 Fen', 'Vestibulumvenenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Hermina Janovsky', '2021-03-16 00:14:23', 5, true, false, 'MarketPost', 25, 4, 20, 7, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (117, 18, 'hting Men', 'Vesttique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Herminia Jaovsky', '2024-03-29 00:14:23', 8, true, false, 'MarketPost', 25, 4, 20, 7, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (118, 19, 'ng Men', 'Veenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Herinia Janosky', '2024-03-28 00:14:23', 1, true, false, 'MarketPost', 25, 4, 20, 7, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (119, 11, '1hting Men', 'Vestist lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'rminia Janovsky', '2014-09-16 00:14:23', 3, true, false, 'MarketPost', 25, 4, 20, 7, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (120, 12, 'ing Men', 'Vesst lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Hernia Janovsky', '2024-03-25 00:14:23', 7, true, false, 'MarketPost', 25, 4, 20, 7, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (121, 13, '13 g Men', 'Vestst lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Henia Janovsky', '2024-03-24 00:14:23', 8, true, false, 'MarketPost', 25, 4, 20, 7, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (122, 14, '13 Fghting Me', 'Vest lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Henia Janovsky', '2024-03-23 00:14:23', 9, true, false, 'MarketPost', 26, 4, 20, 7, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (123, 15, '13ing en', 'lum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Hermininovsky', '2024-03-11 00:14:23', 3, true, false, 'MarketPost', 26, 4, 20, 7, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (124, 16, '13 ghtg Men', 'Vm ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Herminia Jsky', '2024-03-12 00:14:23', 44, true, false, 'MarketPost', 26, 4, 20, 7, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (125, 17, '13 ightig Mn', 'Vestac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Herminia Janovsy', '2024-05-21 00:14:23', 55, true, false, 'MarketPost', 26, 4, 20, 7, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (126, 18, '13 Ftis tri', 'stique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'novsky', '2024-02-22 00:14:23', 11, true, false, 'MarketPost', 26, 4, 20, 7, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (127, 19, '13 Fihtest lacini','a nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Janovsky', '2024-01-26 00:14:23', 12, true, false, 'MarketPost', 25, 4, 20, 7, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (128, 11, '13 ghting Men', 'Vestibu est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Herminia Jaovsky', '2022-11-16 00:14:23', 15, true, false, 'MarketPost', 25, 4, 20, 7, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (129, 12, '13 Fightng Men', 'Vesti lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Herminia anovsky', '2021-01-26 00:14:23', 26, true, false, 'MarketPost', 25, 4, 20, 7, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (130, 13, '13 Fighg Men', ' ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Hermnia Janovsky', '2021-11-30 00:14:23', 33, true, false, 'MarketPost', 25, 4, 20, 7, 0);
insert into common_post (id, user_id, title, content, created_by, created_at, hits, visible, deleted, dtype, category_id, count_of_comments, count_reaction_type_good, count_reaction_type_bad, count_of_reports) values (131, 11, 'ghg Men', ' m id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Hermnia Janovsky', '2021-11-30 00:14:23', 33, true, false, 'MarketPost', 25, 4, 20, 7, 0);


insert into free_post (id, blind_by, blind_at) values (1, 'Staci Hallt', '2024-01-29 00:14:23');
insert into free_post (id, blind_by, blind_at) values (2, 'Zoe Woolmore', '2023-12-30 00:14:23');
insert into free_post (id, blind_by, blind_at) values (3, 'Giselbert Connor', '2023-10-23 00:14:23');
insert into free_post (id, blind_by, blind_at) values (4, 'Abner Grayer', '2023-08-13 00:14:23');
insert into free_post (id, blind_by, blind_at) values (5, 'Sydney Sailes', '2024-02-07 00:14:23');
insert into free_post (id, blind_by, blind_at) values (6, 'Emylee Pauley', '2024-02-29 00:14:23');
insert into free_post (id, blind_by, blind_at) values (7, 'Jolynn Maun', '2023-09-21 00:14:23');
insert into free_post (id, blind_by, blind_at) values (8, 'Leland Ekell', '2023-08-26 00:14:23');
insert into free_post (id, blind_by, blind_at) values (9, 'Dimitri Richards', '2023-08-03 00:14:23');
insert into free_post (id, blind_by, blind_at) values (10, 'Iago Duckels', '2023-09-09 00:14:23');
insert into free_post (id, blind_by, blind_at) values (11, 'Dot Croucher', '2023-12-01 00:14:23');
insert into free_post (id, blind_by, blind_at) values (12, 'Philippe Godbald', '2023-11-26 00:14:23');
insert into free_post (id, blind_by, blind_at) values (13, 'Evey Heartfield', '2023-07-07 00:14:23');
insert into free_post (id, blind_by, blind_at) values (14, 'Bernadene Courvert', '2024-03-03 00:14:23');
insert into free_post (id, blind_by, blind_at) values (15, 'Tisha Minker', '2023-11-28 00:14:23');
insert into free_post (id, blind_by, blind_at) values (16, 'Marcelline Crossdale', '2023-12-15 00:14:23');
insert into free_post (id, blind_by, blind_at) values (17, 'Odell Plester', '2023-07-15 00:14:23');
insert into free_post (id, blind_by, blind_at) values (18, 'Elnora Gatman', '2023-08-07 00:14:23');
insert into free_post (id, blind_by, blind_at) values (19, 'Brinn Kohrsen', '2023-08-25 00:14:23');
insert into free_post (id, blind_by, blind_at) values (20, 'Drucill Santus', '2024-03-25 00:14:23');

-- notice_post
insert into notice_post (id, post_at) values (21, '2024-04-04 00:14:23');
insert into notice_post (id, post_at) values (22, '2024-04-08 00:14:23');
insert into notice_post (id, post_at) values (23, '2023-06-29 00:14:23');
insert into notice_post (id, post_at) values (24, '2023-09-12 00:14:23');
insert into notice_post (id, post_at) values (25, '2023-11-17 00:14:23');
insert into notice_post (id, post_at) values (26, '2024-03-05 00:14:23');
insert into notice_post (id, post_at) values (27, '2023-11-08 00:14:23');
insert into notice_post (id, post_at) values (28, '2023-10-12 00:14:23');
insert into notice_post (id, post_at) values (29, '2023-07-29 00:14:23');
insert into notice_post (id, post_at) values (30, '2023-07-29 00:14:23');
insert into notice_post (id, post_at) values (31, '2024-05-05 00:14:23');
insert into notice_post (id, post_at) values (32, '2024-03-14 00:14:23');
insert into notice_post (id, post_at) values (33, '2023-12-15 00:14:23');
insert into notice_post (id, post_at) values (34, '2023-09-27 00:14:23');
insert into notice_post (id, post_at) values (35, '2024-05-08 00:14:23');
insert into notice_post (id, post_at) values (36, '2024-03-19 00:14:23');
insert into notice_post (id, post_at) values (37, '2024-02-23 00:14:23');
insert into notice_post (id, post_at) values (38, '2023-12-22 00:14:23');
insert into notice_post (id, post_at) values (39, '2024-03-17 00:14:23');
insert into notice_post (id, post_at) values (40, '2024-01-18 00:14:23');

-- notice_post
insert into notice_post (id, is_duty, post_at) values (80, true, '2024-04-04 00:14:23');
insert into notice_post (id, is_duty, post_at) values (81, true, '2024-04-04 00:14:23');
insert into notice_post (id, is_duty, post_at) values (82, true, '2024-04-04 00:14:23');
insert into notice_post (id, is_duty, post_at) values (83, true, '2024-04-04 00:14:23');
insert into notice_post (id, is_duty, post_at) values (84, true, '2024-04-04 00:14:23');
insert into notice_post (id, is_duty, post_at) values (85, true, '2024-04-04 00:14:23');
insert into notice_post (id, is_duty, post_at) values (86, true, '2024-04-04 00:14:23');
insert into notice_post (id, is_duty, post_at) values (87, true, '2024-04-04 00:14:23');
insert into notice_post (id, is_duty, post_at) values (88, true, '2024-04-04 00:14:23');
insert into notice_post (id, is_duty, post_at) values (89, true, '2024-04-04 00:14:23');
insert into notice_post (id, is_duty, post_at) values (90, true, '2024-04-04 00:14:23');
insert into notice_post (id, is_duty, post_at) values (91, true, '2024-04-04 00:14:23');
insert into notice_post (id, is_duty, post_at) values (92, true, '2024-04-04 00:14:23');
insert into notice_post (id, is_duty, post_at) values (93, true, '2024-04-04 00:14:23');
insert into notice_post (id, is_duty, post_at) values (94, true, '2024-04-04 00:14:23');
insert into notice_post (id, is_duty, post_at) values (95, true, '2024-04-04 00:14:23');
insert into notice_post (id, is_duty, post_at) values (96, true, '2024-04-04 00:14:23');
insert into notice_post (id, is_duty, post_at) values (97, true, '2024-04-04 00:14:23');
insert into notice_post (id, is_duty, post_at) values (98, true, '2024-04-04 00:14:23');
insert into notice_post (id, is_duty, post_at) values (99, true, '2024-04-04 00:14:23');
insert into notice_post (id, is_duty, post_at) values (100, true, '2024-04-04 00:14:23');

-- qna_post
insert into qna (id, status) values (41, 'RESPONSE_ACCEPTED');
insert into qna (id, status) values (42, 'AWAITING_RESPONSE');
insert into qna (id, status) values (43, 'AWAITING_RESPONSE');
insert into qna (id, status) values (44, 'AWAITING_RESPONSE');
insert into qna (id, status) values (45, 'AWAITING_RESPONSE');
insert into qna (id, status) values (46, 'AWAITING_RESPONSE');
insert into qna (id, status) values (47, 'AWAITING_RESPONSE');
insert into qna (id, status) values (48, 'AWAITING_RESPONSE');
insert into qna (id, status) values (49, 'AWAITING_RESPONSE');
insert into qna (id, status) values (50, 'AWAITING_RESPONSE');
insert into qna (id, status) values (51, 'AWAITING_RESPONSE');
insert into qna (id, status) values (52, 'AWAITING_RESPONSE');
insert into qna (id, status) values (53, 'AWAITING_RESPONSE');
insert into qna (id, status) values (54, 'AWAITING_RESPONSE');
insert into qna (id, status) values (55, 'AWAITING_RESPONSE');
insert into qna (id, status) values (56, 'AWAITING_RESPONSE');
insert into qna (id, status) values (57, 'AWAITING_RESPONSE');
insert into qna (id, status) values (58, 'AWAITING_RESPONSE');
insert into qna (id, status) values (59, 'AWAITING_RESPONSE');
insert into qna (id, status) values (60, 'AWAITING_RESPONSE');


-- market
insert into market (id, type, status, price) values (101, '중고거래', 'SALE', 1000);
insert into market (id, type, status, price) values (102, '중고거래','SALE', 2000);
insert into market (id, type, status, price) values (103, '중고거래','SALE', 3000);
insert into market (id, type, status, price) values (104, '중고거래','SALE', 4000);
insert into market (id, type, status, price) values (105, '중고거래','SALE', 5000);
insert into market (id, type, status, price) values (106, '무료나눔','SALE', 6000);
insert into market (id, type, status, price) values (107, '무료나눔','SALE', 7000);
insert into market (id, type, status, price) values (108, '무료나눔','SALE', 8000);
insert into market (id, type, status, price) values (109, '무료나눔','SALE', 9000);
insert into market (id, type, status, price) values (110, '무료나눔','SALE', 10000);
insert into market (id, type, status, price) values (111, '중고거래','SOLD_OUT', 0);
insert into market (id, type, status, price) values (112, '중고거래','SOLD_OUT', 1000);
insert into market (id, type, status, price) values (113, '중고거래','SOLD_OUT', 2000);
insert into market (id, type, status, price) values (114, '중고거래','SOLD_OUT', 3000);
insert into market (id, type, status, price) values (115, '중고거래','SOLD_OUT', 4000);
insert into market (id, type, status, price) values (116, '무료나눔','SOLD_OUT', 5000);
insert into market (id, type, status, price) values (117, '무료나눔','SOLD_OUT', 6000);
insert into market (id, type, status, price) values (118, '무료나눔','SOLD_OUT', 7000);
insert into market (id, type, status, price) values (119, '무료나눔','SOLD_OUT', 8000);
insert into market (id, type, status, price) values (120, '무료나눔','SOLD_OUT', 9000);
insert into market (id, type, status, price) values (121, '중고거래','SOLD_OUT', 10000);
insert into market (id, type, status, price) values (122, '중고거래','RESERVED', 1000);
insert into market (id, type, status, price) values (123, '중고거래','RESERVED', 2000);
insert into market (id, type, status, price) values (124, '중고거래','RESERVED', 3000);
insert into market (id, type, status, price) values (125, '중고거래','RESERVED', 4000);
insert into market (id, type, status, price) values (126, '무료나눔','RESERVED', 5000);
insert into market (id, type, status, price) values (127, '무료나눔','RESERVED', 6000);
insert into market (id, type, status, price) values (128, '무료나눔','RESERVED', 7000);
insert into market (id, type, status, price) values (129, '무료나눔','RESERVED', 8000);
insert into market (id, type, status, price) values (130, '무료나눔','RESERVED', 9000);

-- qna comments
insert into comment (post_id,content,created_at,created_by,deleted,is_top,user_id,modified_at,modified_by,parent_comment_id,count_reaction_type_bad,count_reaction_type_good,visible,id, count_of_reports) values (41,'QNA 댓글입니다.','2024-06-02 00:14:23','user',false,false,21,'2024-06-02 00:14:23','user',NULL,0,0,true,default, 0);
insert into comment (post_id,content,created_at,created_by,deleted,is_top,user_id,modified_at,modified_by,parent_comment_id,count_reaction_type_bad,count_reaction_type_good,visible,id, count_of_reports) values (41,'QNA 대 댓글입니다.','2024-06-02 00:14:23','user',false,false,21,'2024-06-02 00:14:23','user',1,0,0,true,default, 0);
insert into comment (post_id,content,created_at,created_by,deleted,is_top,user_id,modified_at,modified_by,parent_comment_id,count_reaction_type_bad,count_reaction_type_good,visible,id, count_of_reports) values (41,'QNA 대 댓글입니다.2','2024-06-02 00:14:23','user',false,false,21,'2024-06-02 00:14:23','user',1,3,0,true,default, 0);
insert into comment (post_id,content,created_at,created_by,deleted,is_top,user_id,modified_at,modified_by,parent_comment_id,count_reaction_type_bad,count_reaction_type_good,visible,id, count_of_reports) values (41,'QNA 어드민 작성 댓글입니다.상단','2024-06-02 00:14:23','admin',false,true,22,'2024-06-02 00:14:23','admin',NULL,1,0,true,default, 0); -- admin comment
insert into comment (post_id,content,created_at,created_by,deleted,is_top,user_id,modified_at,modified_by,parent_comment_id,count_reaction_type_bad,count_reaction_type_good,visible,id, count_of_reports) values (41,'QNA 댓글입니다.3','2024-06-02 00:14:23','user',false,false,21,'2024-06-02 00:14:23','user',NULL,1,0,true,default, 0);
insert into comment (post_id,content,created_at,created_by,deleted,is_top,user_id,modified_at,modified_by,parent_comment_id,count_reaction_type_bad,count_reaction_type_good,visible,id, count_of_reports) values (41,'QNA 댓글입니다.4','2024-06-02 00:14:23','user',false,false,21,'2024-06-02 00:14:23','user',NULL,1,0,true,default, 0);

-- complain comments
insert into comment (post_id,content,created_at,created_by,deleted,is_top,user_id,modified_at,modified_by,parent_comment_id,count_reaction_type_bad,count_reaction_type_good,visible,id, count_of_reports) values (61,'댓글입니다.','2024-06-02 00:14:23','user',false,false,22,'2024-06-02 00:14:23','user',NULL,0,0,true,default, 0);
insert into comment (post_id,content,created_at,created_by,deleted,is_top,user_id,modified_at,modified_by,parent_comment_id,count_reaction_type_bad,count_reaction_type_good,visible,id, count_of_reports) values (61,'대 댓글입니다.','2024-06-02 00:14:23','user',false,false,22,'2024-06-02 00:14:23','user',7,0,0,true,default, 0);
insert into comment (post_id,content,created_at,created_by,deleted,is_top,user_id,modified_at,modified_by,parent_comment_id,count_reaction_type_bad,count_reaction_type_good,visible,id, count_of_reports) values (61,'대 댓글입니다.2','2024-06-02 00:14:23','user',false,false,22,'2024-06-02 00:14:23','user',7,3,0,true,default, 0);
insert into comment (post_id,content,created_at,created_by,deleted,is_top,user_id,modified_at,modified_by,parent_comment_id,count_reaction_type_bad,count_reaction_type_good,visible,id, count_of_reports) values (61,'댓글입니다.2','2024-06-02 00:14:23','admin',false,true,22,'2024-06-02 00:14:23','admin',NULL,1,0,true,default, 0); -- admin comment

insert into reaction(id, user_id, target_id, reaction_type, dtype) values (1, 1, 1, 0, 'PostReaction');
insert into reaction(id, user_id, target_id, reaction_type, dtype) values (2, 1, 2, 1, 'CommentReaction');
insert into reaction(id, user_id, target_id, reaction_type, dtype) values (3, 1, 7, 0, 'CommentReaction');
